version: "3"
services:
  user:
    container_name: pv217_user
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: user-service
    ports:
    - "8081:8081"
    environment:
      quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/d
    depends_on:
      - postgres

  pharmacy:
    container_name: pv217_pharmacy
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: pharmacy-service
    ports:
      - "8082:8082"
    environment:
      quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/d
    depends_on:
      - postgres

  medicine:
    container_name: pv217_medicine
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: user-service
    ports:
      - "8083:8083"
    environment:
      quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/d
    depends_on:
      - postgres

  orders:
    container_name: pv217_orders
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: orders-service
    ports:
      - "8084:8084"
    environment:
      quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/d
      pv217.userService: http://pv217_user:8081
      pv217.pharmacyService: http://pv217_pharmacy:8082
      pv217.medicineService: http://pv217_medicine:8083
    depends_on:
        - postgres

  record:
    container_name: pv217_record
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: record-service
    ports:
      - "8085:8085"
    environment:
      quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/d
    depends_on:
        - postgres

  postgres:
    container_name: postgres
    image: registry.fedoraproject.org/f33/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USER: u
      POSTGRESQL_PASSWORD: p
      POSTGRESQL_DATABASE: d
